SG_WM_zadatak/Models/Proizvod.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SG_WM_zadatak.Models
{
    public class Proizvod
    {
        public int proizvodID { get; set; }
        [Required]
        [StringLength(50,ErrorMessage ="Ne sme biti duzi od 50 karaktera")]
        public string naziv { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "Ne sme biti duzi od 50 karaktera")]
        public string opis { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "Ne sme biti duzi od 50 karaktera")]
        public string kategorija { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "Ne sme biti duzi od 50 karaktera")]
        public string proizvodjac { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "Ne sme biti duzi od 50 karaktera")]
        public string dobavljac { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        public double cena { get; set; }

        public static implicit operator List<object>(Proizvod v)
        {
            throw new NotImplementedException();
        }
    }
}

SG_WM_zadatak/Controllers/ProizvodController.cs
using Newtonsoft.Json;
using SG_WM_zadatak.Config;
using SG_WM_zadatak.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SG_WM_zadatak.Controllers
{
    
    public class ProizvodController : Controller
    {
        // GET: Proizvod
        
        //Baza
        public ActionResult PrikaziIzBaze()
        {
            List<Proizvod> proizvodi = new List<Proizvod>();

            using (SqlConnection con = new SqlConnection(Konekcija.GetKonekcija()))
            {
                using (SqlCommand cmd = new SqlCommand("select* from proizvodi", con))
                {
                    if (con.State != System.Data.ConnectionState.Open)
                    { con.Open(); }
                    SqlDataReader sdr = cmd.ExecuteReader();

                    DataTable dtProizvodi = new DataTable();
                    dtProizvodi.Load(sdr);
                    foreach (DataRow row in dtProizvodi.Rows)
                        proizvodi.Add(
                            new Proizvod
                            {
                                proizvodID = Convert.ToInt32(row["proizvodID"]),
                                naziv = row["naziv"].ToString(),
                                opis = row["opis"].ToString(),
                                kategorija = row["kategorija"].ToString(),
                                proizvodjac = row["proizvodjac"].ToString(),
                                dobavljac = row["dobavljac"].ToString(),
                                cena = Convert.ToDouble(row["cena"])
                            }
                            );
                    }
                }
            return View(proizvodi);           
        }
        public ActionResult Create()
        {

            return View(new Proizvod { proizvodID = 0 });
        }
        [HttpPost]
        public ActionResult Create(Proizvod proizvod)
        {
            if (ModelState.IsValid)
            {
                string insertSQL = "INSERT INTO Proizvodi(naziv,opis,kategorija,proizvodjac,dobavljac,cena) VALUES('" + proizvod.naziv + "', '" + proizvod.opis + "','" + proizvod.kategorija + "','" + proizvod.proizvodjac + "','" + proizvod.dobavljac + "','" + proizvod.cena + "')";
                string updateSQL = "UPDATE Proizvodi SET naziv = '" + proizvod.naziv + "',opis= '" + proizvod.opis + "',kategorija= '" + proizvod.kategorija + "',proizvodjac= '" + proizvod.proizvodjac + "',dobavljac= '" + proizvod.dobavljac + "',cena= '" + proizvod.cena + "' WHERE proizvodID=  '" + proizvod.proizvodID + "' ";


                using (SqlConnection con = new SqlConnection(Konekcija.GetKonekcija()))
                {
                    using (SqlCommand cmd = new SqlCommand
                   ((proizvod.proizvodID > 0) ? updateSQL : insertSQL, con))
                    {
                        if (con.State != System.Data.ConnectionState.Open)
                        { con.Open(); }
                        cmd.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("PrikaziIzBaze");
            }
            
            return View("Create", proizvod);
        }
        public ActionResult Delete(int id)
        {
            if (id < 1) { return HttpNotFound(); }
            using (SqlConnection con = new SqlConnection(Konekcija.GetKonekcija()))
            {
                using (SqlCommand cmd = new SqlCommand("DELETE  FROM Proizvodi WHERE proizvodID = '" + id + "' ", con))
                {
                    if (con.State != ConnectionState.Open) { con.Open(); }

                    cmd.ExecuteNonQuery();
                }
                return RedirectToAction("PrikaziIzBaze");
            }
        }
        public ActionResult Edit(int id)
        {
            if (id < 1) { return HttpNotFound(); }
            var _proizvod = new Proizvod();
            using (SqlConnection con = new SqlConnection(Konekcija.GetKonekcija()))
            {
                using (SqlCommand cmd = new SqlCommand("SELECT * FROM Proizvodi WHERE proizvodID = '" + id + "' ", con))
                {
                    if (con.State != ConnectionState.Open) { con.Open(); }

                    SqlDataReader sdr = cmd.ExecuteReader();
                    DataTable dt = new DataTable();
                    if (sdr.HasRows)
                    {
                        dt.Load(sdr);
                        DataRow row = dt.Rows[0];

                        _proizvod.proizvodID = Convert.ToInt32(row["proizvodID"]);
                        _proizvod.naziv = row["naziv"].ToString();
                        _proizvod.opis = row["opis"].ToString();
                        _proizvod.kategorija = row["kategorija"].ToString();
                        _proizvod.proizvodjac = row["proizvodjac"].ToString();
                        _proizvod.dobavljac = row["dobavljac"].ToString();
                        _proizvod.cena = Convert.ToDouble(row["cena"]);
                        return View("Create", _proizvod);
                    }
                    else { return HttpNotFound(); }
                }
            }
        }

        //JSON      
        public ActionResult PrikaziJson() {

            var WebClient = new WebClient();
            string json = WebClient.DownloadString(@"C:\Users\gagov\source\repos\SG_WM_zadatak\SG_WM_zadatak\JsonFile\rezultat.json");
            ListaProizvoda proizvodi = new ListaProizvoda();
            proizvodi= JsonConvert.DeserializeObject<ListaProizvoda>(json);
           
            return View(proizvodi.listaj);
        }
        public ActionResult CreateJson()
        {

            return View(new Proizvod { proizvodID = 0 });
        }
        [HttpPost]
        public ActionResult CreateJson(Proizvod proizvod)
        {
            if (ModelState.IsValid)
            {
                var WebClient = new WebClient();
                string json = WebClient.DownloadString(@"C:\Users\gagov\source\repos\SG_WM_zadatak\SG_WM_zadatak\JsonFile\rezultat.json");
                ListaProizvoda proizvodi = new ListaProizvoda();
                proizvodi = JsonConvert.DeserializeObject<ListaProizvoda>(json);
                
                if (proizvod.proizvodID == 0)
                {
                    Proizvod pr = proizvodi.listaj.Last();
                    int id = pr.proizvodID + 1;
                    proizvod.proizvodID = id;
                    proizvodi.listaj.Add(proizvod);
                    var pisiJson = JsonConvert.SerializeObject(proizvodi);
                    string fileName = @"C:\Users\gagov\source\repos\SG_WM_zadatak\SG_WM_zadatak\JsonFile\rezultat.json";
                    System.IO.File.WriteAllText(fileName, pisiJson);
                }
                else{
                    foreach (Proizvod pr in proizvodi.listaj) {
                        if (proizvod.proizvodID == pr.proizvodID) {
                            pr.naziv = proizvod.naziv;
                            pr.opis = proizvod.opis;
                            pr.kategorija = proizvod.kategorija;
                            pr.proizvodjac = proizvod.proizvodjac;
                            pr.dobavljac = proizvod.dobavljac;
                            pr.cena = proizvod.cena;
                        }
                    }
                    var pisiJson = JsonConvert.SerializeObject(proizvodi);
                    string fileName = @"C:\Users\gagov\source\repos\SG_WM_zadatak\SG_WM_zadatak\JsonFile\rezultat.json";
                    System.IO.File.WriteAllText(fileName, pisiJson);
                }

                return RedirectToAction("PrikaziJson");
            }
             return View("CreateJson", proizvod);
        }
        public ActionResult EditJson(int id) {
            var WebClient = new WebClient();
            string json = WebClient.DownloadString(@"C:\Users\gagov\source\repos\SG_WM_zadatak\SG_WM_zadatak\JsonFile\rezultat.json");
            ListaProizvoda proizvodi = new ListaProizvoda();
            proizvodi = JsonConvert.DeserializeObject<ListaProizvoda>(json);
            Proizvod vrati = new Proizvod();
            foreach (Proizvod pr in proizvodi.listaj)
            {
                if (id == pr.proizvodID)
                {
                    vrati.proizvodID = pr.proizvodID;
                    vrati.naziv = pr.naziv; 
                    vrati.opis = pr.opis;
                    vrati.kategorija= pr.kategorija;
                    vrati.proizvodjac= pr.proizvodjac;
                    vrati.dobavljac= pr.dobavljac;
                    vrati.cena= pr.cena;
                }
            }


            return View("CreateJson",vrati);
        }
        public ActionResult DeleteJson(int id) {
            var WebClient = new WebClient();
            string json = WebClient.DownloadString(@"C:\Users\gagov\source\repos\SG_WM_zadatak\SG_WM_zadatak\JsonFile\rezultat.json");
            ListaProizvoda proizvodi = new ListaProizvoda();
            proizvodi = JsonConvert.DeserializeObject<ListaProizvoda>(json);

            foreach (Proizvod pr in proizvodi.listaj)
            {
                if (id == pr.proizvodID)
                {
                    proizvodi.listaj.Remove(pr);
                    break;
                }
            }
            var pisiJson = JsonConvert.SerializeObject(proizvodi);
            string fileName = @"C:\Users\gagov\source\repos\SG_WM_zadatak\SG_WM_zadatak\JsonFile\rezultat.json";
            System.IO.File.WriteAllText(fileName, pisiJson);

            return RedirectToAction("PrikaziJson");
        }
    }
}

SG_WM_zadatak/Views/Proizvod/Create.cshtml
@model SG_WM_zadatak.Models.Proizvod

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Proizvod")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proizvod</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kategorija, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kategorija, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kategorija, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.proizvodjac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.proizvodjac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.proizvodjac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dobavljac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dobavljac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dobavljac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                
                @Html.HiddenFor(m => m.proizvodID)
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "PrikaziIzBaze")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SG_WM_zadatak/Views/Proizvod/CreateJson.cshtml
@model SG_WM_zadatak.Models.Proizvod

@{
    ViewBag.Title = "CreateJson";
}

<h2>CreateJson</h2>

@using (Html.BeginForm("CreateJson", "Proizvod"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proizvod</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kategorija, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kategorija, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kategorija, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.proizvodjac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.proizvodjac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.proizvodjac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dobavljac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dobavljac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dobavljac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.HiddenFor(m => m.proizvodID)
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "PrikaziJson")
</div>

SG_WM_zadatak/Views/Proizvod/PrikaziIzBaze.cshtml
@model IEnumerable<SG_WM_zadatak.Models.Proizvod>

@{
    ViewBag.Title = "PrikaziIzBaze";
}

<h2>Prikazi Iz Baze</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kategorija)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.proizvodjac)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dobavljac)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cena)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.opis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kategorija)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.proizvodjac)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dobavljac)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cena)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.proizvodID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.proizvodID })
        </td>
    </tr>
}

</table>

SG_WM_zadatak/Views/Proizvod/PrikaziJson.cshtml
@model IEnumerable<SG_WM_zadatak.Models.Proizvod>

@{
    ViewBag.Title = "PrikaziJson";
}

<h2>Prikazi Json</h2>

<p>
    @Html.ActionLink("Create New", "CreateJson")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kategorija)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.proizvodjac)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dobavljac)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cena)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.opis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kategorija)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.proizvodjac)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dobavljac)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cena)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditJson", new { id=item.proizvodID }) |
            @Html.ActionLink("Delete", "DeleteJson", new { id=item.proizvodID })
        </td>
    </tr>
}

</table>